name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          echo "TEST CML"
    
