name: cml-fashion-mnist
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
       - uses: actions/checkout@v2
       - uses: iterative/setup-cml@v1
       - name: Train model
         run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
       - name: Write CML report
         env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
            # CML Report
            echo "## Fashion Mnist" >> report.md
            echo "### Confusion Matrix" >> report.md
            cml-publish histogram.png --md >> report.md
            echo "### Graph Accuracy" >> report.md
            cml-publish plot_training.png --md >> report.md

            cml-send-comment report.md
