name: cml-fashion-mnist
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "##Fashion Mnist" >> report.md
          echo "###Training / Validation Accuracy" >> report.md
          cml-publish plot_training.png --md >> report.md
          echo "###Confusion Metrics" >> report.md
          cml-publish histogram.png --md >> report.md
          cml-send-comment report.md
